spring:
  shell:
    interactive:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: root
  sql:
    init:
      mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate

    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ROOT: error
