create table authors
(
    id   int8 generated by default as identity,
    name varchar(255) not null,
    primary key (id),
    unique (name)

);

create table styles
(
    id   int8 generated by default as identity,
    name varchar(255) not null,
    primary key (id),
    unique (name)
);

create table books
(
    id        int8 generated by default as identity,
    name      varchar(255) not null,
    author_id int8,
    style_id  int8,
    primary key (id),
    unique (name, author_id, style_id),
    FOREIGN KEY (author_id) REFERENCES authors (id),
    FOREIGN KEY (style_id) REFERENCES public.styles (id)
);